### ISSUE TITLE
   Undefined index: queries

### ISSUE THREAD

**Issue by hmshohrab** [haruncpi/laravel-query-log#1] opened 2022-03-04 08:12 UTC
ErrorException 

  Undefined index: queries

  at vendor/haruncpi/laravel-query-log/src/Supports/TextLogFileWriter.php:19
     15▕         }
     16▕ 
     17▕         $this->writeLine("--------------------\n");
     18▕ 
  ➜  19▕         foreach ($data['queries'] as $q) {
     20▕             foreach ($q as $key => $val) {
     21▕                 if (is_array($val)) {
     22▕                     $this->writeLine($this->addSpace($key, 12) . ": " . implode("|", $val));
     23▕                 } else {

      +9 vendor frames 
  10  artisan:51
      Illuminate\Foundation\Console\Kernel::terminate()

**Comment by haruncpi** [comment] 2022-07-02 06:20
Please let me know your dev env PHP and Laravel version and describe the way to reproduce the error.

**Comment by J87NL** [comment] 2022-08-24 09:37
Hi Haruncpi,

This looks like a nice package, but I've the same error:

APP_ENV=local
APP_DEBUG=true

PHP version: 8.1
Laravel version: 9.23.0

To reproduce: run a custom console command.

Regards,
Johan.

**Comment by wdog** [comment] 2022-09-21 09:02
I have the same problem

**Comment by haruncpi** [comment] 2022-09-22 04:25
This issue has been fixed in v1.0.1

**Closed as completed by haruncpi** 2022-09-22 04:25 UTC
